import { Paper } from '@mantine/core';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react';

import { api } from '@/utils/api';

const WaitingRole = () => {
  const router = useRouter();
  const { data: me, isFetched } = api.user.me.useQuery();
  useEffect(() => {
    if (isFetched) {
      if (me?.onboardingStatus !== 'waitingRole') {
        void router.push('/');
      }
    }
  }, [isFetched, me]);
  return (
    <>
      <Head>
        <title>Waiting</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Paper className="mx-auto mt-16 flex max-w-5xl flex-col items-center p-8">
          <h2 className="font-bold text-green-700">
            Your Role has not been assigned yet.
          </h2>
          <h4>Waiting for role to be assigned.</h4>
          <div>Please contact your Admin if its takes too long. </div>
        </Paper>
      </main>
    </>
  );
};

export default WaitingRole;
