import { Paper } from '@mantine/core';
import Head from 'next/head';
import React from 'react';

import MainLayout from '@/components/layouts/MainLayout';
import TableRoles from '@/components/table/Roles';
import { useRouteGuard } from '@/utils/authorization';

const Roles = () => {
  const { isLoading } = useRouteGuard({
    grantedFor: ['superadmin'],
  });

  if (isLoading) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Roles</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <Paper className="p-8">
            <h2 className="font-bold">Roles</h2>
            <TableRoles />
          </Paper>
        </MainLayout>
      </main>
    </>
  );
};

export default Roles;
